class Arabic {
  Map<String, String> dictionary = {
    'title': 'مرحبا',
    'studentid': 'معرف الطالب',
    'password': 'كلمة المرور',
    'login': 'تسجيل الدخول',
    'logging': 'جاري تسجيل الدخول',
    'forgotPassword?':'نسيت كلمة المرور؟',
    'Notification':'التنبيهات',
    'Table':'الجدول',
    'Home':'الرئيسية',
    'Reports':'التقارير',
    'Profile':'الملف الشخصي',
    'Email':'البريد الالكتروني',
    'UserName':'اسم المستخدم',
    'Phone':'الجوال',
    'Language':'اللغة',
    'Unknown':'غير معروف',
    'Level':'المستوى',
    'News':'الاخبار',
    'Services':'الخدمات',
    'Division':'الشعبة',
    'Department':'القسم',
  };
}
