// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOFAvWOsmpeL_yplL-twY22ONh9t_01hQ',
    appId: '1:153983563829:web:d9eb8c8b4cd2d1c383597c',
    messagingSenderId: '153983563829',
    projectId: 'student-services-91fb5',
    authDomain: 'student-services-91fb5.firebaseapp.com',
    storageBucket: 'student-services-91fb5.firebasestorage.app',
    measurementId: 'G-ZHVZL67HT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjNL0UTTxpdLSDzx0WuWpiUmLAkFGVbrY',
    appId: '1:153983563829:android:c2c5501a83810f5683597c',
    messagingSenderId: '153983563829',
    projectId: 'student-services-91fb5',
    storageBucket: 'student-services-91fb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhiQtI-kyCLbBeA_JlgpCL7gMigMFYaGE',
    appId: '1:153983563829:ios:660772f89fb87e4183597c',
    messagingSenderId: '153983563829',
    projectId: 'student-services-91fb5',
    storageBucket: 'student-services-91fb5.firebasestorage.app',
    iosBundleId: 'com.example.ibbUniversityStudentsServices',
  );

}