// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuEkbL9_sqHwhBovUVHe3EmMbDoA2jCHQ',
    appId: '1:231712318834:web:6b2733231bfc5e654e69eb',
    messagingSenderId: '231712318834',
    projectId: 'unversity-project-2a9e4',
    authDomain: 'unversity-project-2a9e4.firebaseapp.com',
    storageBucket: 'unversity-project-2a9e4.firebasestorage.app',
    measurementId: 'G-0KE3B0KMM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgajg2fSHoq53LoVk8z-8E0hCbQpiaoXQ',
    appId: '1:231712318834:android:959c0bbbc05769ae4e69eb',
    messagingSenderId: '231712318834',
    projectId: 'unversity-project-2a9e4',
    storageBucket: 'unversity-project-2a9e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC2yvQSJrqczFXtkbk2B0QatyFHETAeTE',
    appId: '1:231712318834:ios:77a4a2f8bb6e422a4e69eb',
    messagingSenderId: '231712318834',
    projectId: 'unversity-project-2a9e4',
    storageBucket: 'unversity-project-2a9e4.firebasestorage.app',
    iosBundleId: 'com.example.ibbUniversityStudentsServices',
  );
}
